package tidal.client;

public enum SendStatus {
	SEND_OK,
	SERVER_ERROR,
	SERVER_BUSY,
	REQUEST_CODE_NOT_SUPPORTED,
    FLUSH_DISK_TIMEOUT,
    TOPIC_EXISTED,
    TOPIC_NOT_EXISTED,
    PLOY_NOT_SUPPORTED,
    INIT_VALUE_INVALID,
    CLASS_NOT_FOUND,
    PLOY_CLASS_MAPPING_ERROR,
    FLUSH_DISK_FULL,
    PASSWORD_ERROR
}
